language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

script:
    - cargo build --verbose --all
    - cargo test --verbose --all
    - cargo test --verbose -p ensicoin_serializer

cache: cargo

notifications:
    webhooks: https://discordapp.com/api/webhooks/536610527837683734/FPnSdX31qA_c5q0Ctr_pPiYK-Q5vFZnUhdX3RPA3rcCdDFBZRP3mjLKlk4tsUdSRsS6m
