[package]
name = "another-rust-coin"
version = "0.1.0"
authors = ["Quentin Boyer <qbsecond@gmail.com>"]
edition = "2018"

[dependencies]
ensicoin_serializer = "0.2.0"
log = "0.4"
simplelog = "^0.5.0"
clap = "2.32.0"
