[package]
name = "another-rust-coin"
version = "0.1.0"
authors = ["Quentin Boyer <qbsecond@gmail.com>"]
edition = "2018"

[dependencies]
ensicoin_serializer = "0.1.2"
log = "0.4"
pretty_env_logger = "0.3"
